# Title shown in Application Information tab.
title: Traefik Proxy
# Sub Title shown in Application Information tab.
description:  The Cloud Native Application Proxy
schemaVersion: 1.1.0
version: "20190304"

# URL of Logo Icon used on Application Information tab. You can copy the contentId from the Marketplace listing logo URL in the Marketplace Partner portal.
# (Optional)
logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=181108816

# Used in Application Information tab to Hyperlink Title and Logo to the Marketplace
# Listing.
# Also used to link to Listing Usage section for "View Instructions".
# (Optional) If it is missing, Application Information uses the
# "marketplace-listing-id" tag for the same purpose.
source:
  type: marketplace
  reference: 181108699

locale: "en"
variableGroups:
  - title: "Hidden Variable Group"
    visible: false
    variables:
#"variables used internally - not exposed to end user"
      - tenancy_ocid
      - region
      - marketplace_source_images
      - mp_listing_id
      - mp_listing_resource_id
      - mp_listing_resource_version
      - mp_subscription_enabled

  - title: "OKE Configuration"
    variables:
      - oke_cluster_create
      - oke_insecure

  - title: "Create basic OKE"
    variables:
      - oke_cluster_name
    visible: ${oke_cluster_create}

  - title: "Use existing OKE"
    variables:
      - oke_cluster_id
    visible:
      not:
        - ${oke_cluster_create}

  - title: "Chart Configuration"
    variables:
      - chart_namespace
      - chart_values

######################################################
##############    HIDDEN VARIABLES       #############
######################################################

variables:

  tenancy_ocid:
    type: string
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: The region in which to create all resources
    required: true

######################################################
##############    REQUIRED VARIABLES     #############
######################################################

  oke_cluster_id:
    type: string
    title: OKE Cluster ID
    description: The ID of the OKE cluster

  oke_cluster_create:
    type: boolean
    title: Create basic OKE Cluster
    description: 3 nodes (VM.Standard.E3.Flex) / 2 OCPU / 4 GB RAM / latest OKE version

  oke_cluster_name:
    type: string
    title: Name of OKE Cluster to create
    default: traefik-demo
    minLength: 1
    maxLength: 25
    pattern: "^[a-z][a-zA-Z0-9-]+$"

  oke_insecure:
    type: boolean
    title: Allow insecure connection
    description: It may be needed on private OKE cluster

  chart_values:
    type: text
    required: true
    multiline: true
    title: Traefik Helm Chart values
    description: "See https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md"

  chart_namespace:
    type: string
    required: false
    title: Target namespace

#############################################
###########    OUTPUT GROUPS     ############
#############################################

outputGroups:
  - title: "Chart output"
    outputs:
      - chart_version
      - chart_status
      - chart_notes


#############################################
##############     OUTPUTS     ##############
#############################################

outputs:
  chart_version:
    type: string
    title: Version
    visible: true

  chart_status:
    type: string
    title: Status
    visible: true

  chart_notes:
    type: string
    title: Notes
    visible: true

# primaryOutputButton is a reference to a link output that creates a primary button
# on the Application Information tab.
# (Optional) if not provided, no primary button is shown.  Also if the output
# referenced is not a link output, no button is shown.
# primaryOutputButton:
